[build]
  command = "npm run generate"
  publish = "dist"

[[redirects]]
  from = "/api/guestbook"
  to = "/.netlify/functions/handle-form"
  status = 200
  force = true
  conditions = {Method = ["POST"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 